
image:
  file: .gitpod.Dockerfile
tasks:
  - name: Configure AWS
    init: aws --version
    command: |
      echo "To configure AWS, run: aws configure"
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace 
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT


